# Site settings
title: Reefsource
email: vram@stanford.edu
description: Crowdsourced data collection for coral reef health reporting
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: BrownInstitute 
github_username: 

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"

gems:
  - jekyll-paginate